$(document).ready(function(){
    $(".header_mobile-menu").click(function(){
      $(".menuList").slideToggle(1);
    });
  });
$(document).ready(function(){
    $(".productMobile_menu").click(function(){
      $(".productMobile_list").slideToggle(1);
    });
  });